@address = http://localhost:8080

###
# valid zipcode
GET {{address}}/cep?cep=01001000 HTTP/1.1
Host: localhost:8080
Accept: application/json, text/plain, */*
Content-Type: application/json

###
# valid zipcode
GET {{address}}/cep?cep=80050250 HTTP/1.1
Host: localhost:8080
Accept: application/json, text/plain, */*
Content-Type: application/json

###
# can not find zipcode
GET {{address}}/cep?cep=99950250 HTTP/1.1
Host: localhost:8080
Accept: application/json, text/plain, */*
Content-Type: application/json

###
# invalid zipcode
GET {{address}}/cep?cep=9995025 HTTP/1.1
Host: localhost:8080
Accept: application/json, text/plain, */*
Content-Type: application/json